[2025-01-10T17:31:38.060+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T17:31:38.074+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-01-10T17:31:36.188714+00:00 [queued]>
[2025-01-10T17:31:38.080+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-01-10T17:31:36.188714+00:00 [queued]>
[2025-01-10T17:31:38.080+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T17:31:38.089+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2025-01-10 17:31:36.188714+00:00
[2025-01-10T17:31:38.095+0000] {standard_task_runner.py:72} INFO - Started process 61 to run task
[2025-01-10T17:31:38.102+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2025-01-10T17:31:36.188714+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/reddis_dag.py', '--cfg-path', '/tmp/tmpifu84_wo']
[2025-01-10T17:31:38.103+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask reddit_extraction
[2025-01-10T17:31:38.168+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2025-01-10T17:31:36.188714+00:00 [running]> on host 78ffa1533b0a
[2025-01-10T17:31:38.413+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kritya Shree Sivasakthi' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T17:31:36.188714+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T17:31:36.188714+00:00'
[2025-01-10T17:31:38.417+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T17:31:38.440+0000] {logging_mixin.py:190} INFO - name 'client_secret' is not defined
[2025-01-10T17:31:38.441+0000] {taskinstance.py:3313} ERROR - Task failed due to SystemExit(1)
[2025-01-10T17:31:38.447+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2025-01-10T17:31:36.188714+00:00, execution_date=20250110T173136, start_date=20250110T173138, end_date=20250110T173138
[2025-01-10T17:31:38.456+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T17:31:38.457+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 8 for task reddit_extraction (Task failed due to SystemExit(1); 61)
Traceback (most recent call last):
  File "/opt/airflow/etls/reddit_etl.py", line 10, in connect_reddit
    client_secret=client_secret,
NameError: name 'client_secret' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 7, in reddit_pipeline
    instance = connect_reddit(CLIENT_ID, SECRET, 'Airscholar Agent')
  File "/opt/airflow/etls/reddit_etl.py", line 16, in connect_reddit
    sys.exit(1)
  File "/home/airflow/.local/lib/python3.9/site-packages/billiard/pool.py", line 283, in exit
    return _exit(status)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 334, in _run_raw_task
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Task failed due to SystemExit(1)
[2025-01-10T17:31:38.494+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-10T17:31:38.512+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T17:31:38.513+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
